### ISSUE TITLE
Resolve error => LossTensor is inf or nan. : Tensor had NaN values

### ISSUE THREAD

**Issue by tomassosorio** [tomassosorio/DeepLearning#20]
python train.py  --logtostderr --train_dir=/home/tomas/Documents/Pessoal/CODE/DeepLearning/model/logs --pipeline_config_path=/home/tomas/Documents/Pessoal/CODE/DeepLearning/model/ssd_mobilnet_v1_coco.config
INFO:tensorflow:Summary name Learning Rate is illegal; using Learning_Rate instead.
INFO:tensorflow:Summary name /clone_loss is illegal; using clone_loss instead.
2017-10-30 11:03:56.492621: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-30 11:03:56.492672: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-30 11:03:56.492686: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-30 11:03:56.492693: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-30 11:03:56.492700: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
INFO:tensorflow:Restoring parameters from /home/tomas/Documents/Pessoal/CODE/DeepLearning/model/logs/model.ckpt-1
2017-10-30 11:03:57.078987: I tensorflow/core/common_runtime/simple_placer.cc:697] Ignoring device specification /device:GPU:0 for node 'prefetch_queue_Dequeue' because the input edge from 'prefetch_queue' is a reference connection and already has a device field set to /device:CPU:0
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path /home/tomas/Documents/Pessoal/CODE/DeepLearning/model/logs/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Recording summary at step 1.
INFO:tensorflow:global step 2: loss = 0.3317 (4.537 sec/step)
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, LossTensor is inf or nan. : Tensor had NaN values
	 [[Node: CheckNumerics = CheckNumerics[T=DT_FLOAT, message="LossTensor is inf or nan.", _device="/job:localhost/replica:0/task:0/cpu:0"](total_loss)]]

Caused by op u'CheckNumerics', defined at:
  File "train.py", line 198, in <module>
    tf.app.run()
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/tomas/Documents/Pessoal/TESE/models-master/research/object_detection/trainer.py", line 227, in train
    total_loss = tf.check_numerics(total_loss, 'LossTensor is inf or nan.')
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 413, in check_numerics
    message=message, name=name)
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): LossTensor is inf or nan. : Tensor had NaN values
	 [[Node: CheckNumerics = CheckNumerics[T=DT_FLOAT, message="LossTensor is inf or nan.", _device="/job:localhost/replica:0/task:0/cpu:0"](total_loss)]]

Traceback (most recent call last):
  File "train.py", line 198, in <module>
    tf.app.run()
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/tomas/Documents/Pessoal/TESE/models-master/research/object_detection/trainer.py", line 296, in train
    saver=saver)
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 755, in train
    sess, train_op, global_step, train_step_kwargs)
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 488, in train_step
    run_metadata=run_metadata)
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: LossTensor is inf or nan. : Tensor had NaN values
	 [[Node: CheckNumerics = CheckNumerics[T=DT_FLOAT, message="LossTensor is inf or nan.", _device="/job:localhost/replica:0/task:0/cpu:0"](total_loss)]]

Caused by op u'CheckNumerics', defined at:
  File "train.py", line 198, in <module>
    tf.app.run()
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/tomas/Documents/Pessoal/TESE/models-master/research/object_detection/trainer.py", line 227, in train
    total_loss = tf.check_numerics(total_loss, 'LossTensor is inf or nan.')
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 413, in check_numerics
    message=message, name=name)
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/tomas/tf-cpu/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): LossTensor is inf or nan. : Tensor had NaN values
	 [[Node: CheckNumerics = CheckNumerics[T=DT_FLOAT, message="LossTensor is inf or nan.", _device="/job:localhost/replica:0/task:0/cpu:0"](total_loss)]]

**Comment by tomassosorio** [comment]
https://stackoverflow.com/questions/47018349/tensorflow-object-detection-api-kitti-dataset-error-tensor-had-nan-values

**Comment by miguelriemoliveira** [comment]
For now we will close this issue and work on PyTorch.

If necessary will reopen issue.
